#%RAML 1.0 NamedExample

  value:
    addressid: 0,
    amount: 0,
    created: 
      date: 0,
      day: 0,
      hours: 0,
      minutes: 0,
      month: 0,
      nanos: 0,
      seconds: 0,
      time: 0,
      timezoneOffset: 0,
      year: 0
    
    discountid": 0,
    modified": 
      date: 0,
      day: 0,
      hours: 0,
      minutes: 0,
      month: 0,
      nanos: 0,
      seconds: 0,
      time: 0,
      timezoneOffset": 0,
      year: 0
    
    orderid: 0,
    status: string,
    userid: 0
  
