#%RAML 1.0 NamedExample
ordersExample:value:
  addressid: 101
  amount: 999
  created: 
    date: 05/28/2020
    day: Monday
    hours: 10
    minutes: 20
    month: 05
    nanos: 00
    seconds: 05
    time: 8-10
    timezoneOffset: 2
    year: 2020
  discountid: 105
  modified: 
    date: 04/16/2020
    day: 16
    hours: 12   
    minutes: 25
    month: 04
    nanos: 00
    seconds: 15
    time: 02:30
    timezoneOffset: 2
    year: 2020
  orderid: 103
  status: Active
  userid: 16