#%RAML 1.0 NamedExample
productsExample:value:
- categoryid: 120
  description: Galaxy
  name: Phone
  price: 900
  productid: 1651
  video_url: https://www.samsung.com/us/galaxy/why-galaxy/
- categoryid: 125
  description: Galaxy
  name: Phone
  price: 900
  productid: 1652
  video_url: https://www.samsung.com/us/galaxy/why-galaxy/
