#%RAML 1.0 NamedExample
productByIDExample:value:
  productid: 1651
  categoryid: 120
  name: Galaxy Phone
  description: With the uncertain timeline of social distancing, we want to ease your mind. Rest assured we will honor all manufacturer warranties that expire between April 1 and June 30, 2020 – just call, text or chat to let us know.*
  video_url: https://www.samsung.com/us/galaxy/why-galaxy/
  price: 999