#%RAML 1.0 NamedExample
OrderExample NOID:
  [
  {
    "addressid":1000,
    "amount": 10000,
    "created": {
      "date": 1-1-2020,
      "day": Monday,
      "hours": 12:00AM,
      "minutes": 06:00,
      "month": 01,
      "nanos": 0,
      "seconds": 00:00:01,
      "time": 12:06:01,
      "timezoneOffset": 0,
      "year": 2020
    },
    "discountid": 12,
    "modified": {
      "date": 4-20-2020,
      "day": 0,
      "hours": 0,
      "minutes": 0,
      "month": 4,
      "nanos": 0,
      "seconds": 0,
      "time": 0,
      "timezoneOffset": 0,
      "year": 2020
    },
    "orderid": 200,
    "status": "Shipping",
    "userid": 1000
  }
]
