#%RAML 1.0 NamedExample

value:
  [
  {
    "categoryid": 12,
    "description": "Wireless-AC + Blutooth4.1,best battry life,",
    "name": "Microsoft Surface laptop",
    "price": 10000,
    "productid": 10,
    "video_url": "https://www.microsoft.com"
  }
]